# Generated by Django 3.2.19 on 2024-02-16 04:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid

from qmoney_payment.models.policy import is_from_policy_app, get_fully_qualified_name_of_policy_model


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    if is_from_policy_app():
        dependencies.append(('policy', '0008_policyrenewalmutation'))

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id',
                 models.AutoField(db_column='PolicyID',
                                  primary_key=True,
                                  serialize=False)),
                ('uuid',
                 models.CharField(db_column='PolicyUUID',
                                  default=uuid.uuid4,
                                  max_length=36,
                                  unique=True)),
                ('status',
                 models.SmallIntegerField(blank=True,
                                          db_column='PolicyStatus',
                                          null=True)),
            ],
            options={
                'db_table': 'tblPolicy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QMoneyPayment',
            fields=[
                ('uuid',
                 models.UUIDField(default=uuid.uuid4,
                                  editable=False,
                                  primary_key=True,
                                  serialize=False)),
                ('contribution_uuid', models.UUIDField(blank=True, null=True)),
                ('external_transaction_id',
                 models.CharField(blank=True, max_length=200, null=True)),
                ('status',
                 models.CharField(choices=[('INITIATED', 'I'),
                                           ('WAITING_FOR_CONFIRMATION', 'W'),
                                           ('PROCEEDED', 'P'),
                                           ('UNKNOWN', 'U'), ('FAILED', 'F')],
                                  default='INITIATED',
                                  max_length=32)),
                ('amount',
                 models.IntegerField(
                     default=0,
                     validators=[django.core.validators.MinValueValidator(0)
                                 ])),
                ('payer_wallet', models.CharField(max_length=200)),
                ('policy',
                 models.ForeignKey(
                     blank=True,
                     null=True,
                     on_delete=django.db.models.deletion.CASCADE,
                     to=get_fully_qualified_name_of_policy_model())),
            ],
            options={
                'db_table': 'tblQmoneyPayment',
                'managed': True,
            },
        ),
    ]
