# Generated by Django 3.2.24 on 2024-04-17 07:02

from django.db import migrations

from core.utils import remove_role_right_for_system, insert_role_right_for_system

from qmoney_payment.apps import DEFAULT_CONFIG

ROLE_ID = 64
RIGHTS = [code[0] for name, code in DEFAULT_CONFIG.items()]


def add_query_rights(_apps, _schema_editor):
    for right in RIGHTS:
        insert_role_right_for_system(ROLE_ID, right)


def remove_query_rights(_apps, _schema_editor):
    for right in RIGHTS:
        remove_role_right_for_system(ROLE_ID, right)


class Migration(migrations.Migration):

    dependencies = [
        ('qmoney_payment', '0002_auto_20240412_0930'),
    ]

    operations = [
        migrations.RunPython(add_query_rights, remove_query_rights),
    ]
